POST http://localhost:8080/user/new
Content-Type: application/json

{
  "username": "newBBeautifulUser",
  "password": "passwordCorrect",
  "email": "newe@main.com"
}


###
POST http://localhost:8080/user/remove?id=48569ea9-5759-44b2-92cc-04694f56d38f
Content-Type: application/json


###
PUT http://localhost:8080/user/edit
Content-Type: application/json

{
  "userId": "70f479b2-5eab-42fc-9b56-a676158918b3",
  "fieldName": "username",
  "newValue": "BadName"
}

###
GET http://localhost:8080/user/search
Content-Type: application/json







