POST http://localhost:8080/user/new
Content-Type: application/json

{
  "username": "newdBBddeautifulUser",
  "password": "passrdCoect",
  "email": "newe@maidn.com"
}

###
POST http://localhost:8080/user/remove?id=10178d45-ee90-4fb9-823c-aefd83240fd3
Content-Type: application/json

###
PUT http://localhost:8080/user/edit
Content-Type: application/json

{
  "userId": "70f479b2-5eab-42fc-9b56-a676158918b3",
  "fieldName": "username",
  "newValue": "BadName"
}

###
GET http://localhost:8080/user/search?removed=true
Content-Type: application/json







