version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'db-container'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=java'